import { Platform } from 'react-native';
import { IThemeAtom, IThemeCommonAtom } from '../types';
import fonts from '../common/fonts';
import commonAtom from '../common/atom';
import colors from './colors';

const fontFamily = Platform.select({ android: 'sans-serif', ios: 'Helvetica' });
const fontWeightRegular = 'normal';
const fontWeightBold = 'bold';

const atom: IThemeAtom & IThemeCommonAtom = {
  ...commonAtom,
  text1: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size1,
    lineHeight: fonts.lineHeight1,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text1b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size1,
    lineHeight: fonts.lineHeight1,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  text2: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size2,
    lineHeight: fonts.lineHeight2,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text2b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size2,
    lineHeight: fonts.lineHeight2,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  text3: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size3,
    lineHeight: fonts.lineHeight3,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text3b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size3,
    lineHeight: fonts.lineHeight3,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  text4: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size4,
    lineHeight: fonts.lineHeight4,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text4b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size4,
    lineHeight: fonts.lineHeight4,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  text5: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size5,
    lineHeight: fonts.lineHeight5,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text5b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size5,
    lineHeight: fonts.lineHeight5,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  text6: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size6,
    lineHeight: fonts.lineHeight6,
    fontStyle: 'normal',
    fontWeight: fontWeightRegular,
  },
  text6b: {
    fontFamily,
    color: colors.fontGray2,
    fontSize: fonts.size6,
    lineHeight: fonts.lineHeight6,
    fontStyle: 'normal',
    fontWeight: fontWeightBold,
  },
  // ================  边框  ===================
  b0: { borderWidth: 0 },
  b1: { borderWidth: 1, borderStyle: 'solid', borderColor: colors.gray2 },
  bb1: { borderBottomWidth: 1, borderStyle: 'solid', borderColor: colors.gray2 },
  bt1: { borderTopWidth: 1, borderStyle: 'solid', borderColor: colors.gray2 },
  br1: { borderRightWidth: 1, borderStyle: 'solid', borderColor: colors.gray2 },
  bl1: { borderLeftWidth: 1, borderStyle: 'solid', borderColor: colors.gray2 },

  // ================  背景色  ===================
  bg: { backgroundColor: colors.white },
  bgBrand7: { backgroundColor: colors.brand7 },
  bgBrand1: { backgroundColor: colors.brand1 },
  bgGray1: { backgroundColor: colors.gray1 },
  bgGray2: { backgroundColor: colors.gray2 },
  bgBlueGray1: { backgroundColor: colors.blueGray1 },
  bgBlueGray2: { backgroundColor: colors.blueGray2 },
  bgSuccess: { backgroundColor: colors.success5 },
  bgWarning: { backgroundColor: colors.warning4 },
  bgError: { backgroundColor: colors.error6 },

  // ================  字体颜色  ===================
  white: { color: colors.white },
  gray1: { color: colors.gray1 },
  gray2: { color: colors.gray2 },
  gray3: { color: colors.gray3 },
  gray4: { color: colors.gray4 },
  gray5: { color: colors.gray5 },
  gray6: { color: colors.gray6 },
  gray7: { color: colors.gray7 },
  gray8: { color: colors.gray8 },
  gray9: { color: colors.gray9 },
  gray10: { color: colors.gray10 },
  gray11: { color: colors.gray11 },
  gray12: { color: colors.gray12 },
  gray13: { color: colors.gray13 },
  gray14: { color: colors.gray14 },
  brand1: { color: colors.brand1 },
  brand2: { color: colors.brand2 },
  brand3: { color: colors.brand3 },
  brand4: { color: colors.brand4 },
  brand5: { color: colors.brand5 },
  brand6: { color: colors.brand6 },
  brand7: { color: colors.brand7 },
  brand8: { color: colors.brand8 },
  brand9: { color: colors.brand9 },
  brand10: { color: colors.brand10 },
  blueGray1: { color: colors.blueGray1 },
  blueGray2: { color: colors.blueGray2 },
  blueGray3: { color: colors.blueGray3 },
  blueGray4: { color: colors.blueGray4 },
  blueGray5: { color: colors.blueGray5 },
  blueGray6: { color: colors.blueGray6 },
  blueGray7: { color: colors.blueGray7 },
  blueGray8: { color: colors.blueGray8 },
  blueGray9: { color: colors.blueGray9 },
  blueGray10: { color: colors.blueGray10 },
  blueGray11: { color: colors.blueGray11 },
  blueGray12: { color: colors.blueGray12 },
  blueGray13: { color: colors.blueGray13 },
  blueGray14: { color: colors.blueGray14 },
  success5: { color: colors.success5 },
  warning4: { color: colors.warning4 },
  error6: { color: colors.error6 },
  fontGray1: { color: colors.fontGray1 },
  fontGray2: { color: colors.fontGray2 },
  fontGray3: { color: colors.fontGray3 },
  fontGray4: { color: colors.fontGray4 },
  fontWhite1: { color: colors.fontWhite1 },
  fontWhite2: { color: colors.fontWhite2 },
  fontWhite3: { color: colors.fontWhite3 },
  fontWhite4: { color: colors.fontWhite4 },
};

export default atom;
