import { classnames as commonClassNames } from '../common/classnames';
import { Spacers } from '../common/spacers';
import { colors } from './colors';

export const classnames: any = {
  ...commonClassNames,
  text1: {
    ...commonClassNames.text1,
    color: colors.fontGray2,
  },
  text1b: {
    ...commonClassNames.text1b,
    color: colors.fontGray2,
  },
  text2: {
    ...commonClassNames.text2,
    color: colors.fontGray2,
  },
  text2b: {
    ...commonClassNames.text2b,
    color: colors.fontGray2,
  },
  text3: {
    ...commonClassNames.text3,
    color: colors.fontGray2,
  },
  text3b: {
    ...commonClassNames.text3b,
    color: colors.fontGray2,
  },
  text4: {
    ...commonClassNames.text4,
    color: colors.fontGray2,
  },
  text4b: {
    ...commonClassNames.text4b,
    color: colors.fontGray2,
  },
  text5: {
    ...commonClassNames.text5,
    color: colors.fontGray2,
  },
  text5b: {
    ...commonClassNames.text5b,
    color: colors.fontGray2,
  },
  text6: {
    ...commonClassNames.text6,
    color: colors.fontGray2,
  },
  text6b: {
    ...commonClassNames.text6b,
    color: colors.fontGray2,
  },
  text7: {
    ...commonClassNames.text7,
    color: colors.fontGray2,
  },
  text7b: {
    ...commonClassNames.text7b,
    color: colors.fontGray2,
  },

  // ================  边框  ===================
  b0: { borderWidth: Spacers.spacer0 },
  b1: {
    borderWidth: Spacers.spacer1,
    borderStyle: 'solid',
    borderColor: colors.componentBorder,
  },
  bb1: {
    borderBottomWidth: Spacers.spacer1,
    borderStyle: 'solid',
    borderColor: colors.componentBorder,
  },
  bt1: {
    borderTopWidth: Spacers.spacer1,
    borderStyle: 'solid',
    borderColor: colors.componentBorder,
  },
  br1: {
    borderRightWidth: Spacers.spacer1,
    borderStyle: 'solid',
    borderColor: colors.componentBorder,
  },
  bl1: {
    borderLeftWidth: Spacers.spacer1,
    borderStyle: 'solid',
    borderColor: colors.componentBorder,
  },

  // ================  背景色  ===================
  bg: { backgroundColor: colors.bgContainer },
  bgPage: { backgroundColor: colors.bgPage },
  bgContainer: { backgroundColor: colors.bgContainer },
  bgContainerHover: { backgroundColor: colors.bgContainerHover },
  bgContainerActive: { backgroundColor: colors.bgContainerActive },
  bgContainerSelect: { backgroundColor: colors.bgContainerSelect },
  bgSubContainer: { backgroundColor: colors.bgSubContainer },
  bgSubContainerHover: { backgroundColor: colors.bgSubContainerHover },
  bgSubContainerActive: { backgroundColor: colors.bgSubContainerActive },
  bgComponent: { backgroundColor: colors.bgComponent },
  bgComponentHover: { backgroundColor: colors.bgComponentHover },
  bgComponentActive: { backgroundColor: colors.bgComponentActive },
  bgComponentDisabled: { backgroundColor: colors.bgComponentDisabled },
  bgSubComponent: { backgroundColor: colors.bgSubComponent },
  bgSubComponentHover: { backgroundColor: colors.bgSubComponentHover },
  bgSubComponentActive: { backgroundColor: colors.bgSubComponentActive },

  // ================  字体颜色  ===================
  white: { color: colors.white },
  brand1: { color: colors.brand1 },
  brand2: { color: colors.brand2 },
  brand3: { color: colors.brand3 },
  brand4: { color: colors.brand4 },
  brand5: { color: colors.brand5 },
  brand6: { color: colors.brand6 },
  brand7: { color: colors.brand7 },
  brand8: { color: colors.brand8 },
  brand9: { color: colors.brand9 },
  brand10: { color: colors.brand10 },
  brand: { color: colors.brand },
  brandLight: { color: colors.brandLight },
  brandFocus: { color: colors.brandFocus },
  brandDisabled: { color: colors.brandDisabled },
  brandHover: { color: colors.brandHover },
  brandActive: { color: colors.brandActive },

  error1: { color: colors.error1 },
  error2: { color: colors.error2 },
  error3: { color: colors.error3 },
  error4: { color: colors.error4 },
  error5: { color: colors.error5 },
  error6: { color: colors.error6 },
  error7: { color: colors.error7 },
  error8: { color: colors.error8 },
  error9: { color: colors.error9 },
  error10: { color: colors.error10 },
  error: { color: colors.error },
  errorLight: { color: colors.errorLight },
  errorFocus: { color: colors.errorFocus },
  errorDisabled: { color: colors.errorDisabled },
  errorHover: { color: colors.errorHover },
  errorActive: { color: colors.errorActive },

  success1: { color: colors.success1 },
  success2: { color: colors.success2 },
  success3: { color: colors.success3 },
  success4: { color: colors.success4 },
  success5: { color: colors.success5 },
  success6: { color: colors.success6 },
  success7: { color: colors.success7 },
  success8: { color: colors.success8 },
  success9: { color: colors.success9 },
  success10: { color: colors.success10 },
  success: { color: colors.success },
  successLight: { color: colors.successLight },
  successFocus: { color: colors.successFocus },
  successDisabled: { color: colors.successDisabled },
  successHover: { color: colors.successHover },
  successActive: { color: colors.successActive },

  warning1: { color: colors.warning1 },
  warning2: { color: colors.warning2 },
  warning3: { color: colors.warning3 },
  warning4: { color: colors.warning4 },
  warning5: { color: colors.warning5 },
  warning6: { color: colors.warning6 },
  warning7: { color: colors.warning7 },
  warning8: { color: colors.warning8 },
  warning9: { color: colors.warning9 },
  warning10: { color: colors.warning10 },
  warning: { color: colors.warning },
  warningLight: { color: colors.warningLight },
  warningFocus: { color: colors.warningFocus },
  warningDisabled: { color: colors.warningDisabled },
  warningHover: { color: colors.warningHover },
  warningActive: { color: colors.warningActive },

  gray1: { color: colors.gray1 },
  gray2: { color: colors.gray2 },
  gray3: { color: colors.gray3 },
  gray4: { color: colors.gray4 },
  gray5: { color: colors.gray5 },
  gray6: { color: colors.gray6 },
  gray7: { color: colors.gray7 },
  gray8: { color: colors.gray8 },
  gray9: { color: colors.gray9 },
  gray10: { color: colors.gray10 },
  gray11: { color: colors.gray11 },
  gray12: { color: colors.gray12 },
  gray13: { color: colors.gray13 },
  gray14: { color: colors.gray14 },
};
