import { LightColors } from './colors';
import { CommonTokens } from '../common/tokens';

export const lightTokens = {
  ...CommonTokens,
  colors: {
    white: LightColors.white,
    brand1: LightColors.brand1,
    brand2: LightColors.brand2,
    brand3: LightColors.brand3,
    brand4: LightColors.brand4,
    brand5: LightColors.brand5,
    brand6: LightColors.brand6,
    brand7: LightColors.brand7,
    brand8: LightColors.brand8,
    brand9: LightColors.brand9,
    brand10: LightColors.brand10,
    brand: LightColors.brand7,
    brandLight: LightColors.brand1,
    brandFocus: LightColors.brand2,
    brandDisabled: LightColors.brand3,
    brandHover: LightColors.brand6,
    brandActive: LightColors.brand8,

    error1: LightColors.error1,
    error2: LightColors.error2,
    error3: LightColors.error3,
    error4: LightColors.error4,
    error5: LightColors.error5,
    error6: LightColors.error6,
    error7: LightColors.error7,
    error8: LightColors.error8,
    error9: LightColors.error9,
    error10: LightColors.error10,
    error: LightColors.error6,
    errorLight: LightColors.error1,
    errorFocus: LightColors.error2,
    errorDisabled: LightColors.error3,
    errorHover: LightColors.error5,
    errorActive: LightColors.error7,

    success1: LightColors.success1,
    success2: LightColors.success2,
    success3: LightColors.success3,
    success4: LightColors.success4,
    success5: LightColors.success5,
    success6: LightColors.success6,
    success7: LightColors.success7,
    success8: LightColors.success8,
    success9: LightColors.success9,
    success10: LightColors.success10,
    success: LightColors.success5,
    successLight: LightColors.success1,
    successFocus: LightColors.success2,
    successDisabled: LightColors.success3,
    successHover: LightColors.success4,
    successActive: LightColors.success6,

    warning1: LightColors.warning1,
    warning2: LightColors.warning2,
    warning3: LightColors.warning3,
    warning4: LightColors.warning4,
    warning5: LightColors.warning5,
    warning6: LightColors.warning6,
    warning7: LightColors.warning7,
    warning8: LightColors.warning8,
    warning9: LightColors.warning9,
    warning10: LightColors.warning10,
    warning: LightColors.warning5,
    warningLight: LightColors.warning1,
    warningFocus: LightColors.warning2,
    warningDisabled: LightColors.warning3,
    warningHover: LightColors.warning4,
    warningActive: LightColors.warning6,

    gray1: LightColors.gray1,
    gray2: LightColors.gray2,
    gray3: LightColors.gray3,
    gray4: LightColors.gray4,
    gray5: LightColors.gray5,
    gray6: LightColors.gray6,
    gray7: LightColors.gray7,
    gray8: LightColors.gray8,
    gray9: LightColors.gray9,
    gray10: LightColors.gray10,
    gray11: LightColors.gray11,
    gray12: LightColors.gray12,
    gray13: LightColors.gray13,
    gray14: LightColors.gray14,

    bgPage: LightColors.gray2,
    bgContainer: LightColors.white,
    bgContainerHover: LightColors.gray1,
    bgContainerActive: LightColors.gray3,
    bgContainerSelect: LightColors.white,
    bgSubContainer: LightColors.gray1,
    bgSubContainerHover: LightColors.gray2,
    bgSubContainerActive: LightColors.gray4,
    bgComponent: LightColors.gray3,
    bgComponentHover: LightColors.gray4,
    bgComponentActive: LightColors.gray6,
    bgComponentDisabled: LightColors.gray2,
    bgSubComponent: LightColors.gray4,
    bgSubComponentHover: LightColors.gray5,
    bgSubComponentActive: LightColors.gray6,

    componentStroke: LightColors.gray3,
    componentBorder: LightColors.gray4,

    fontWhite1: LightColors.fontWhite1,
    fontWhite2: LightColors.fontWhite2,
    fontWhite3: LightColors.fontWhite3,
    fontWhite4: LightColors.fontWhite4,

    fontGray1: LightColors.fontGray1,
    fontGray2: LightColors.fontGray2,
    fontGray3: LightColors.fontGray3,
    fontGray4: LightColors.fontGray4,

    textPrimary: LightColors.fontGray1,
    textSecondary: LightColors.fontGray2,
    textPlaceholder: LightColors.fontGray3,
    textDisabled: LightColors.fontGray4,
    textAnti: LightColors.white,
    textBrand: LightColors.brand7,
    textLink: LightColors.brand7,

    shadow1: LightColors.shadow1,
    shadow2: LightColors.shadow2,
    shadow3: LightColors.shadow3,
  },
};
