import { IThemeCommonAtom } from '../types';
import spacers from './spacers';
import dimensions from './dimensions';

const atom: IThemeCommonAtom = {
  // ================  内边距  ===================
  p0: { padding: spacers.spacer0 },
  p4: { padding: spacers.spacer4 },
  p8: { padding: spacers.spacer8 },
  p12: { padding: spacers.spacer12 },
  p16: { padding: spacers.spacer16 },
  p24: { padding: spacers.spacer24 },
  p32: { padding: spacers.spacer32 },
  p40: { padding: spacers.spacer40 },
  p48: { padding: spacers.spacer48 },
  p64: { padding: spacers.spacer64 },
  p96: { padding: spacers.spacer96 },
  p160: { padding: spacers.spacer160 },

  pb0: { paddingBottom: spacers.spacer0 },
  pb4: { paddingBottom: spacers.spacer4 },
  pb8: { paddingBottom: spacers.spacer8 },
  pb12: { paddingBottom: spacers.spacer12 },
  pb16: { paddingBottom: spacers.spacer16 },
  pb24: { paddingBottom: spacers.spacer24 },
  pb32: { paddingBottom: spacers.spacer32 },
  pb40: { paddingBottom: spacers.spacer40 },
  pb48: { paddingBottom: spacers.spacer48 },
  pb64: { paddingBottom: spacers.spacer64 },
  pb96: { paddingBottom: spacers.spacer96 },
  pb160: { paddingBottom: spacers.spacer160 },

  pl0: { paddingLeft: spacers.spacer0 },
  pl4: { paddingLeft: spacers.spacer4 },
  pl8: { paddingLeft: spacers.spacer8 },
  pl12: { paddingLeft: spacers.spacer12 },
  pl16: { paddingLeft: spacers.spacer16 },
  pl24: { paddingLeft: spacers.spacer24 },
  pl32: { paddingLeft: spacers.spacer32 },
  pl40: { paddingLeft: spacers.spacer40 },
  pl48: { paddingLeft: spacers.spacer48 },
  pl64: { paddingLeft: spacers.spacer64 },
  pl96: { paddingLeft: spacers.spacer96 },
  pl160: { paddingLeft: spacers.spacer160 },

  pr0: { paddingRight: spacers.spacer0 },
  pr4: { paddingRight: spacers.spacer4 },
  pr8: { paddingRight: spacers.spacer8 },
  pr12: { paddingRight: spacers.spacer12 },
  pr16: { paddingRight: spacers.spacer16 },
  pr24: { paddingRight: spacers.spacer24 },
  pr32: { paddingRight: spacers.spacer32 },
  pr40: { paddingRight: spacers.spacer40 },
  pr48: { paddingRight: spacers.spacer48 },
  pr64: { paddingRight: spacers.spacer64 },
  pr96: { paddingRight: spacers.spacer96 },
  pr160: { paddingRight: spacers.spacer160 },

  pt0: { paddingTop: spacers.spacer0 },
  pt4: { paddingTop: spacers.spacer4 },
  pt8: { paddingTop: spacers.spacer8 },
  pt12: { paddingTop: spacers.spacer12 },
  pt16: { paddingTop: spacers.spacer16 },
  pt24: { paddingTop: spacers.spacer24 },
  pt32: { paddingTop: spacers.spacer32 },
  pt40: { paddingTop: spacers.spacer40 },
  pt48: { paddingTop: spacers.spacer48 },
  pt64: { paddingTop: spacers.spacer64 },
  pt96: { paddingTop: spacers.spacer96 },
  pt160: { paddingTop: spacers.spacer160 },

  px0: { paddingHorizontal: spacers.spacer0 },
  px4: { paddingHorizontal: spacers.spacer4 },
  px8: { paddingHorizontal: spacers.spacer8 },
  px12: { paddingHorizontal: spacers.spacer12 },
  px16: { paddingHorizontal: spacers.spacer16 },
  px24: { paddingHorizontal: spacers.spacer24 },
  px32: { paddingHorizontal: spacers.spacer32 },
  px40: { paddingHorizontal: spacers.spacer40 },
  px48: { paddingHorizontal: spacers.spacer48 },
  px64: { paddingHorizontal: spacers.spacer64 },
  px96: { paddingHorizontal: spacers.spacer96 },
  px160: { paddingHorizontal: spacers.spacer160 },

  py0: { paddingVertical: spacers.spacer0 },
  py4: { paddingVertical: spacers.spacer4 },
  py8: { paddingVertical: spacers.spacer8 },
  py12: { paddingVertical: spacers.spacer12 },
  py16: { paddingVertical: spacers.spacer16 },
  py24: { paddingVertical: spacers.spacer24 },
  py32: { paddingVertical: spacers.spacer32 },
  py40: { paddingVertical: spacers.spacer40 },
  py48: { paddingVertical: spacers.spacer48 },
  py64: { paddingVertical: spacers.spacer64 },
  py96: { paddingVertical: spacers.spacer96 },
  py160: { paddingVertical: spacers.spacer160 },

  // ================  外边距  ===================
  m0: { margin: spacers.spacer0 },
  m4: { margin: spacers.spacer4 },
  m8: { margin: spacers.spacer8 },
  m12: { margin: spacers.spacer12 },
  m16: { margin: spacers.spacer16 },
  m24: { margin: spacers.spacer24 },
  m32: { margin: spacers.spacer32 },
  m40: { margin: spacers.spacer40 },
  m48: { margin: spacers.spacer48 },
  m64: { margin: spacers.spacer64 },
  m96: { margin: spacers.spacer96 },
  m160: { margin: spacers.spacer160 },

  mb0: { marginBottom: spacers.spacer0 },
  mb4: { marginBottom: spacers.spacer4 },
  mb8: { marginBottom: spacers.spacer8 },
  mb12: { marginBottom: spacers.spacer12 },
  mb16: { marginBottom: spacers.spacer16 },
  mb24: { marginBottom: spacers.spacer24 },
  mb32: { marginBottom: spacers.spacer32 },
  mb40: { marginBottom: spacers.spacer40 },
  mb48: { marginBottom: spacers.spacer48 },
  mb64: { marginBottom: spacers.spacer64 },
  mb96: { marginBottom: spacers.spacer96 },
  mb160: { marginBottom: spacers.spacer160 },

  mt0: { marginTop: spacers.spacer0 },
  mt4: { marginTop: spacers.spacer4 },
  mt8: { marginTop: spacers.spacer8 },
  mt12: { marginTop: spacers.spacer12 },
  mt16: { marginTop: spacers.spacer16 },
  mt24: { marginTop: spacers.spacer24 },
  mt32: { marginTop: spacers.spacer32 },
  mt40: { marginTop: spacers.spacer40 },
  mt48: { marginTop: spacers.spacer48 },
  mt64: { marginTop: spacers.spacer64 },
  mt96: { marginTop: spacers.spacer96 },
  mt160: { marginTop: spacers.spacer160 },

  ml0: { marginLeft: spacers.spacer0 },
  ml4: { marginLeft: spacers.spacer4 },
  ml8: { marginLeft: spacers.spacer8 },
  ml12: { marginLeft: spacers.spacer12 },
  ml16: { marginLeft: spacers.spacer16 },
  ml24: { marginLeft: spacers.spacer24 },
  ml32: { marginLeft: spacers.spacer32 },
  ml40: { marginLeft: spacers.spacer40 },
  ml48: { marginLeft: spacers.spacer48 },
  ml64: { marginLeft: spacers.spacer64 },
  ml96: { marginLeft: spacers.spacer96 },
  ml160: { marginLeft: spacers.spacer160 },

  mr0: { marginRight: spacers.spacer0 },
  mr4: { marginRight: spacers.spacer4 },
  mr8: { marginRight: spacers.spacer8 },
  mr12: { marginRight: spacers.spacer12 },
  mr16: { marginRight: spacers.spacer16 },
  mr24: { marginRight: spacers.spacer24 },
  mr32: { marginRight: spacers.spacer32 },
  mr40: { marginRight: spacers.spacer40 },
  mr48: { marginRight: spacers.spacer48 },
  mr64: { marginRight: spacers.spacer64 },
  mr96: { marginRight: spacers.spacer96 },
  mr160: { marginRight: spacers.spacer160 },

  mx0: { marginHorizontal: spacers.spacer0 },
  mx4: { marginHorizontal: spacers.spacer4 },
  mx8: { marginHorizontal: spacers.spacer8 },
  mx12: { marginHorizontal: spacers.spacer12 },
  mx16: { marginHorizontal: spacers.spacer16 },
  mx24: { marginHorizontal: spacers.spacer24 },
  mx32: { marginHorizontal: spacers.spacer32 },
  mx40: { marginHorizontal: spacers.spacer40 },
  mx48: { marginHorizontal: spacers.spacer48 },
  mx64: { marginHorizontal: spacers.spacer64 },
  mx96: { marginHorizontal: spacers.spacer96 },
  mx160: { marginHorizontal: spacers.spacer160 },

  my0: { marginVertical: spacers.spacer0 },
  my4: { marginVertical: spacers.spacer4 },
  my8: { marginVertical: spacers.spacer8 },
  my12: { marginVertical: spacers.spacer12 },
  my16: { marginVertical: spacers.spacer16 },
  my24: { marginVertical: spacers.spacer24 },
  my32: { marginVertical: spacers.spacer32 },
  my40: { marginVertical: spacers.spacer40 },
  my48: { marginVertical: spacers.spacer48 },
  my64: { marginVertical: spacers.spacer64 },
  my96: { marginVertical: spacers.spacer96 },
  my160: { marginVertical: spacers.spacer160 },

  // ================  flex  ===================
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  flex3: { flex: 3 },
  flex: { display: 'flex' },
  flexRow: { flexDirection: 'row' },
  flexCol: { flexDirection: 'column' },
  flexCenter: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
  flexCenterH: { display: 'flex', justifyContent: 'center' },
  flexCenterV: { display: 'flex', alignItems: 'center' },
  flexBetween: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  flexBetweenH: { display: 'flex', justifyContent: 'space-between' },
  flexAround: { display: 'flex', justifyContent: 'space-around', alignItems: 'center' },
  flexAroundH: { display: 'flex', justifyContent: 'space-around' },
  flexEnd: { display: 'flex', alignItems: 'flex-end', justifyContent: 'center' },
  flexEndH: { display: 'flex', justifyContent: 'flex-end' },
  flexEndV: { display: 'flex', alignItems: 'flex-end' },
  flexStart: { display: 'flex', alignItems: 'flex-start', justifyContent: 'center' },
  flexStartH: { display: 'flex', justifyContent: 'flex-start' },
  flexStartV: { display: 'flex', alignItems: 'flex-start' },

  // ================  圆角  ===================
  radius: { borderRadius: dimensions.borderRadius },
  radius2: { borderRadius: dimensions.borderRadius2 },
  radius4: { borderRadius: dimensions.borderRadius4 },
  radius8: { borderRadius: dimensions.borderRadius8 },
  radiusFull: { borderRadius: dimensions.borderRadiusFull },

  // ================  对齐  ===================
  textCenter: { textAlign: 'center' },
  textRight: { textAlign: 'right' },
  textLeft: { textAlign: 'left' },

  // ================  显示  ===================
  hidden: { display: 'none' },
};

export default atom;
