// import { IThemeCommonAtom } from '../types';
import { Platform } from 'react-native';
import { CommonTokens } from './tokens';

const fontFamily = Platform.select({ android: 'sans-serif', ios: 'Helvetica' });

export const classnames = {
  // ================  内边距  ===================
  p0: { padding: CommonTokens.spacers.spacer0 },
  p2: { padding: CommonTokens.spacers.spacer2 },
  p4: { padding: CommonTokens.spacers.spacer4 },
  p6: { padding: CommonTokens.spacers.spacer6 },
  p8: { padding: CommonTokens.spacers.spacer8 },
  p10: { padding: CommonTokens.spacers.spacer10 },
  p12: { padding: CommonTokens.spacers.spacer12 },
  p14: { padding: CommonTokens.spacers.spacer14 },
  p16: { padding: CommonTokens.spacers.spacer16 },
  p18: { padding: CommonTokens.spacers.spacer18 },
  p20: { padding: CommonTokens.spacers.spacer20 },
  p22: { padding: CommonTokens.spacers.spacer22 },
  p24: { padding: CommonTokens.spacers.spacer24 },
  p26: { padding: CommonTokens.spacers.spacer26 },
  p28: { padding: CommonTokens.spacers.spacer28 },
  p30: { padding: CommonTokens.spacers.spacer30 },
  p32: { padding: CommonTokens.spacers.spacer32 },
  p36: { padding: CommonTokens.spacers.spacer36 },
  p40: { padding: CommonTokens.spacers.spacer40 },
  p44: { padding: CommonTokens.spacers.spacer44 },
  p48: { padding: CommonTokens.spacers.spacer48 },

  pb0: { paddingBottom: CommonTokens.spacers.spacer0 },
  pb2: { paddingBottom: CommonTokens.spacers.spacer2 },
  pb4: { paddingBottom: CommonTokens.spacers.spacer4 },
  pb6: { paddingBottom: CommonTokens.spacers.spacer6 },
  pb8: { paddingBottom: CommonTokens.spacers.spacer8 },
  pb10: { paddingBottom: CommonTokens.spacers.spacer10 },
  pb12: { paddingBottom: CommonTokens.spacers.spacer12 },
  pb14: { paddingBottom: CommonTokens.spacers.spacer14 },
  pb16: { paddingBottom: CommonTokens.spacers.spacer16 },
  pb18: { paddingBottom: CommonTokens.spacers.spacer18 },
  pb20: { paddingBottom: CommonTokens.spacers.spacer20 },
  pb22: { paddingBottom: CommonTokens.spacers.spacer22 },
  pb24: { paddingBottom: CommonTokens.spacers.spacer24 },
  pb26: { paddingBottom: CommonTokens.spacers.spacer26 },
  pb28: { paddingBottom: CommonTokens.spacers.spacer28 },
  pb30: { paddingBottom: CommonTokens.spacers.spacer30 },
  pb32: { paddingBottom: CommonTokens.spacers.spacer32 },
  pb36: { paddingBottom: CommonTokens.spacers.spacer36 },
  pb40: { paddingBottom: CommonTokens.spacers.spacer40 },
  pb44: { paddingBottom: CommonTokens.spacers.spacer44 },
  pb48: { paddingBottom: CommonTokens.spacers.spacer48 },

  pt0: { paddingTop: CommonTokens.spacers.spacer0 },
  pt2: { paddingTop: CommonTokens.spacers.spacer2 },
  pt4: { paddingTop: CommonTokens.spacers.spacer4 },
  pt6: { paddingTop: CommonTokens.spacers.spacer6 },
  pt8: { paddingTop: CommonTokens.spacers.spacer8 },
  pt10: { paddingTop: CommonTokens.spacers.spacer10 },
  pt12: { paddingTop: CommonTokens.spacers.spacer12 },
  pt14: { paddingTop: CommonTokens.spacers.spacer14 },
  pt16: { paddingTop: CommonTokens.spacers.spacer16 },
  pt18: { paddingTop: CommonTokens.spacers.spacer18 },
  pt20: { paddingTop: CommonTokens.spacers.spacer20 },
  pt22: { paddingTop: CommonTokens.spacers.spacer22 },
  pt24: { paddingTop: CommonTokens.spacers.spacer24 },
  pt26: { paddingTop: CommonTokens.spacers.spacer26 },
  pt28: { paddingTop: CommonTokens.spacers.spacer28 },
  pt30: { paddingTop: CommonTokens.spacers.spacer30 },
  pt32: { paddingTop: CommonTokens.spacers.spacer32 },
  pt36: { paddingTop: CommonTokens.spacers.spacer36 },
  pt40: { paddingTop: CommonTokens.spacers.spacer40 },
  pt44: { paddingTop: CommonTokens.spacers.spacer44 },
  pt48: { paddingTop: CommonTokens.spacers.spacer48 },

  pl0: { paddingLeft: CommonTokens.spacers.spacer0 },
  pl2: { paddingLeft: CommonTokens.spacers.spacer2 },
  pl4: { paddingLeft: CommonTokens.spacers.spacer4 },
  pl6: { paddingLeft: CommonTokens.spacers.spacer6 },
  pl8: { paddingLeft: CommonTokens.spacers.spacer8 },
  pl10: { paddingLeft: CommonTokens.spacers.spacer10 },
  pl12: { paddingLeft: CommonTokens.spacers.spacer12 },
  pl14: { paddingLeft: CommonTokens.spacers.spacer14 },
  pl16: { paddingLeft: CommonTokens.spacers.spacer16 },
  pl18: { paddingLeft: CommonTokens.spacers.spacer18 },
  pl20: { paddingLeft: CommonTokens.spacers.spacer20 },
  pl22: { paddingLeft: CommonTokens.spacers.spacer22 },
  pl24: { paddingLeft: CommonTokens.spacers.spacer24 },
  pl26: { paddingLeft: CommonTokens.spacers.spacer26 },
  pl28: { paddingLeft: CommonTokens.spacers.spacer28 },
  pl30: { paddingLeft: CommonTokens.spacers.spacer30 },
  pl32: { paddingLeft: CommonTokens.spacers.spacer32 },
  pl36: { paddingLeft: CommonTokens.spacers.spacer36 },
  pl40: { paddingLeft: CommonTokens.spacers.spacer40 },
  pl44: { paddingLeft: CommonTokens.spacers.spacer44 },
  pl48: { paddingLeft: CommonTokens.spacers.spacer48 },

  pr0: { paddingRight: CommonTokens.spacers.spacer0 },
  pr2: { paddingRight: CommonTokens.spacers.spacer2 },
  pr4: { paddingRight: CommonTokens.spacers.spacer4 },
  pr6: { paddingRight: CommonTokens.spacers.spacer6 },
  pr8: { paddingRight: CommonTokens.spacers.spacer8 },
  pr10: { paddingRight: CommonTokens.spacers.spacer10 },
  pr12: { paddingRight: CommonTokens.spacers.spacer12 },
  pr14: { paddingRight: CommonTokens.spacers.spacer14 },
  pr16: { paddingRight: CommonTokens.spacers.spacer16 },
  pr18: { paddingRight: CommonTokens.spacers.spacer18 },
  pr20: { paddingRight: CommonTokens.spacers.spacer20 },
  pr22: { paddingRight: CommonTokens.spacers.spacer22 },
  pr24: { paddingRight: CommonTokens.spacers.spacer24 },
  pr26: { paddingRight: CommonTokens.spacers.spacer26 },
  pr28: { paddingRight: CommonTokens.spacers.spacer28 },
  pr30: { paddingRight: CommonTokens.spacers.spacer30 },
  pr32: { paddingRight: CommonTokens.spacers.spacer32 },
  pr36: { paddingRight: CommonTokens.spacers.spacer36 },
  pr40: { paddingRight: CommonTokens.spacers.spacer40 },
  pr44: { paddingRight: CommonTokens.spacers.spacer44 },
  pr48: { paddingRight: CommonTokens.spacers.spacer48 },

  px0: { paddingHorizontal: CommonTokens.spacers.spacer0 },
  px2: { paddingHorizontal: CommonTokens.spacers.spacer2 },
  px4: { paddingHorizontal: CommonTokens.spacers.spacer4 },
  px6: { paddingHorizontal: CommonTokens.spacers.spacer6 },
  px8: { paddingHorizontal: CommonTokens.spacers.spacer8 },
  px10: { paddingHorizontal: CommonTokens.spacers.spacer10 },
  px12: { paddingHorizontal: CommonTokens.spacers.spacer12 },
  px14: { paddingHorizontal: CommonTokens.spacers.spacer14 },
  px16: { paddingHorizontal: CommonTokens.spacers.spacer16 },
  px18: { paddingHorizontal: CommonTokens.spacers.spacer18 },
  px20: { paddingHorizontal: CommonTokens.spacers.spacer20 },
  px22: { paddingHorizontal: CommonTokens.spacers.spacer22 },
  px24: { paddingHorizontal: CommonTokens.spacers.spacer24 },
  px26: { paddingHorizontal: CommonTokens.spacers.spacer26 },
  px28: { paddingHorizontal: CommonTokens.spacers.spacer28 },
  px30: { paddingHorizontal: CommonTokens.spacers.spacer30 },
  px32: { paddingHorizontal: CommonTokens.spacers.spacer32 },
  px36: { paddingHorizontal: CommonTokens.spacers.spacer36 },
  px40: { paddingHorizontal: CommonTokens.spacers.spacer40 },
  px44: { paddingHorizontal: CommonTokens.spacers.spacer44 },
  px48: { paddingHorizontal: CommonTokens.spacers.spacer48 },

  py0: { paddingVertical: CommonTokens.spacers.spacer0 },
  py2: { paddingVertical: CommonTokens.spacers.spacer2 },
  py4: { paddingVertical: CommonTokens.spacers.spacer4 },
  py6: { paddingVertical: CommonTokens.spacers.spacer6 },
  py8: { paddingVertical: CommonTokens.spacers.spacer8 },
  py10: { paddingVertical: CommonTokens.spacers.spacer10 },
  py12: { paddingVertical: CommonTokens.spacers.spacer12 },
  py14: { paddingVertical: CommonTokens.spacers.spacer14 },
  py16: { paddingVertical: CommonTokens.spacers.spacer16 },
  py18: { paddingVertical: CommonTokens.spacers.spacer18 },
  py20: { paddingVertical: CommonTokens.spacers.spacer20 },
  py22: { paddingVertical: CommonTokens.spacers.spacer22 },
  py24: { paddingVertical: CommonTokens.spacers.spacer24 },
  py26: { paddingVertical: CommonTokens.spacers.spacer26 },
  py28: { paddingVertical: CommonTokens.spacers.spacer28 },
  py30: { paddingVertical: CommonTokens.spacers.spacer30 },
  py32: { paddingVertical: CommonTokens.spacers.spacer32 },
  py36: { paddingVertical: CommonTokens.spacers.spacer36 },
  py40: { paddingVertical: CommonTokens.spacers.spacer40 },
  py44: { paddingVertical: CommonTokens.spacers.spacer44 },
  py48: { paddingVertical: CommonTokens.spacers.spacer48 },

  // ================  外边距  ===================
  m0: { margin: CommonTokens.spacers.spacer0 },
  m2: { margin: CommonTokens.spacers.spacer2 },
  m4: { margin: CommonTokens.spacers.spacer4 },
  m6: { margin: CommonTokens.spacers.spacer6 },
  m8: { margin: CommonTokens.spacers.spacer8 },
  m10: { margin: CommonTokens.spacers.spacer10 },
  m12: { margin: CommonTokens.spacers.spacer12 },
  m14: { margin: CommonTokens.spacers.spacer14 },
  m16: { margin: CommonTokens.spacers.spacer16 },
  m18: { margin: CommonTokens.spacers.spacer18 },
  m20: { margin: CommonTokens.spacers.spacer20 },
  m22: { margin: CommonTokens.spacers.spacer22 },
  m24: { margin: CommonTokens.spacers.spacer24 },
  m26: { margin: CommonTokens.spacers.spacer26 },
  m28: { margin: CommonTokens.spacers.spacer28 },
  m30: { margin: CommonTokens.spacers.spacer30 },
  m32: { margin: CommonTokens.spacers.spacer32 },
  m36: { margin: CommonTokens.spacers.spacer36 },
  m40: { margin: CommonTokens.spacers.spacer40 },
  m44: { margin: CommonTokens.spacers.spacer44 },
  m48: { margin: CommonTokens.spacers.spacer48 },

  mb0: { marginBottom: CommonTokens.spacers.spacer0 },
  mb2: { marginBottom: CommonTokens.spacers.spacer2 },
  mb4: { marginBottom: CommonTokens.spacers.spacer4 },
  mb6: { marginBottom: CommonTokens.spacers.spacer6 },
  mb8: { marginBottom: CommonTokens.spacers.spacer8 },
  mb10: { marginBottom: CommonTokens.spacers.spacer10 },
  mb12: { marginBottom: CommonTokens.spacers.spacer12 },
  mb14: { marginBottom: CommonTokens.spacers.spacer14 },
  mb16: { marginBottom: CommonTokens.spacers.spacer16 },
  mb18: { marginBottom: CommonTokens.spacers.spacer18 },
  mb20: { marginBottom: CommonTokens.spacers.spacer20 },
  mb22: { marginBottom: CommonTokens.spacers.spacer22 },
  mb24: { marginBottom: CommonTokens.spacers.spacer24 },
  mb26: { marginBottom: CommonTokens.spacers.spacer26 },
  mb28: { marginBottom: CommonTokens.spacers.spacer28 },
  mb30: { marginBottom: CommonTokens.spacers.spacer30 },
  mb32: { marginBottom: CommonTokens.spacers.spacer32 },
  mb36: { marginBottom: CommonTokens.spacers.spacer36 },
  mb40: { marginBottom: CommonTokens.spacers.spacer40 },
  mb44: { marginBottom: CommonTokens.spacers.spacer44 },
  mb48: { marginBottom: CommonTokens.spacers.spacer48 },

  mt0: { marginTop: CommonTokens.spacers.spacer0 },
  mt2: { marginTop: CommonTokens.spacers.spacer2 },
  mt4: { marginTop: CommonTokens.spacers.spacer4 },
  mt6: { marginTop: CommonTokens.spacers.spacer6 },
  mt8: { marginTop: CommonTokens.spacers.spacer8 },
  mt10: { marginTop: CommonTokens.spacers.spacer10 },
  mt12: { marginTop: CommonTokens.spacers.spacer12 },
  mt14: { marginTop: CommonTokens.spacers.spacer14 },
  mt16: { marginTop: CommonTokens.spacers.spacer16 },
  mt18: { marginTop: CommonTokens.spacers.spacer18 },
  mt20: { marginTop: CommonTokens.spacers.spacer20 },
  mt22: { marginTop: CommonTokens.spacers.spacer22 },
  mt24: { marginTop: CommonTokens.spacers.spacer24 },
  mt26: { marginTop: CommonTokens.spacers.spacer26 },
  mt28: { marginTop: CommonTokens.spacers.spacer28 },
  mt30: { marginTop: CommonTokens.spacers.spacer30 },
  mt32: { marginTop: CommonTokens.spacers.spacer32 },
  mt36: { marginTop: CommonTokens.spacers.spacer36 },
  mt40: { marginTop: CommonTokens.spacers.spacer40 },
  mt44: { marginTop: CommonTokens.spacers.spacer44 },
  mt48: { marginTop: CommonTokens.spacers.spacer48 },

  ml0: { marginLeft: CommonTokens.spacers.spacer0 },
  ml2: { marginLeft: CommonTokens.spacers.spacer2 },
  ml4: { marginLeft: CommonTokens.spacers.spacer4 },
  ml6: { marginLeft: CommonTokens.spacers.spacer6 },
  ml8: { marginLeft: CommonTokens.spacers.spacer8 },
  ml10: { marginLeft: CommonTokens.spacers.spacer10 },
  ml12: { marginLeft: CommonTokens.spacers.spacer12 },
  ml14: { marginLeft: CommonTokens.spacers.spacer14 },
  ml16: { marginLeft: CommonTokens.spacers.spacer16 },
  ml18: { marginLeft: CommonTokens.spacers.spacer18 },
  ml20: { marginLeft: CommonTokens.spacers.spacer20 },
  ml22: { marginLeft: CommonTokens.spacers.spacer22 },
  ml24: { marginLeft: CommonTokens.spacers.spacer24 },
  ml26: { marginLeft: CommonTokens.spacers.spacer26 },
  ml28: { marginLeft: CommonTokens.spacers.spacer28 },
  ml30: { marginLeft: CommonTokens.spacers.spacer30 },
  ml32: { marginLeft: CommonTokens.spacers.spacer32 },
  ml36: { marginLeft: CommonTokens.spacers.spacer36 },
  ml40: { marginLeft: CommonTokens.spacers.spacer40 },
  ml44: { marginLeft: CommonTokens.spacers.spacer44 },
  ml48: { marginLeft: CommonTokens.spacers.spacer48 },

  mr0: { marginRight: CommonTokens.spacers.spacer0 },
  mr2: { marginRight: CommonTokens.spacers.spacer2 },
  mr4: { marginRight: CommonTokens.spacers.spacer4 },
  mr6: { marginRight: CommonTokens.spacers.spacer6 },
  mr8: { marginRight: CommonTokens.spacers.spacer8 },
  mr10: { marginRight: CommonTokens.spacers.spacer10 },
  mr12: { marginRight: CommonTokens.spacers.spacer12 },
  mr14: { marginRight: CommonTokens.spacers.spacer14 },
  mr16: { marginRight: CommonTokens.spacers.spacer16 },
  mr18: { marginRight: CommonTokens.spacers.spacer18 },
  mr20: { marginRight: CommonTokens.spacers.spacer20 },
  mr22: { marginRight: CommonTokens.spacers.spacer22 },
  mr24: { marginRight: CommonTokens.spacers.spacer24 },
  mr26: { marginRight: CommonTokens.spacers.spacer26 },
  mr28: { marginRight: CommonTokens.spacers.spacer28 },
  mr30: { marginRight: CommonTokens.spacers.spacer30 },
  mr32: { marginRight: CommonTokens.spacers.spacer32 },
  mr36: { marginRight: CommonTokens.spacers.spacer36 },
  mr40: { marginRight: CommonTokens.spacers.spacer40 },
  mr44: { marginRight: CommonTokens.spacers.spacer44 },
  mr48: { marginRight: CommonTokens.spacers.spacer48 },

  mx0: { marginHorizontal: CommonTokens.spacers.spacer0 },
  mx2: { marginHorizontal: CommonTokens.spacers.spacer2 },
  mx4: { marginHorizontal: CommonTokens.spacers.spacer4 },
  mx6: { marginHorizontal: CommonTokens.spacers.spacer6 },
  mx8: { marginHorizontal: CommonTokens.spacers.spacer8 },
  mx10: { marginHorizontal: CommonTokens.spacers.spacer10 },
  mx12: { marginHorizontal: CommonTokens.spacers.spacer12 },
  mx14: { marginHorizontal: CommonTokens.spacers.spacer14 },
  mx16: { marginHorizontal: CommonTokens.spacers.spacer16 },
  mx18: { marginHorizontal: CommonTokens.spacers.spacer18 },
  mx20: { marginHorizontal: CommonTokens.spacers.spacer20 },
  mx22: { marginHorizontal: CommonTokens.spacers.spacer22 },
  mx24: { marginHorizontal: CommonTokens.spacers.spacer24 },
  mx26: { marginHorizontal: CommonTokens.spacers.spacer26 },
  mx28: { marginHorizontal: CommonTokens.spacers.spacer28 },
  mx30: { marginHorizontal: CommonTokens.spacers.spacer30 },
  mx32: { marginHorizontal: CommonTokens.spacers.spacer32 },
  mx36: { marginHorizontal: CommonTokens.spacers.spacer36 },
  mx40: { marginHorizontal: CommonTokens.spacers.spacer40 },
  mx44: { marginHorizontal: CommonTokens.spacers.spacer44 },
  mx48: { marginHorizontal: CommonTokens.spacers.spacer48 },

  my0: { marginVertical: CommonTokens.spacers.spacer0 },
  my2: { marginVertical: CommonTokens.spacers.spacer2 },
  my4: { marginVertical: CommonTokens.spacers.spacer4 },
  my6: { marginVertical: CommonTokens.spacers.spacer6 },
  my8: { marginVertical: CommonTokens.spacers.spacer8 },
  my10: { marginVertical: CommonTokens.spacers.spacer10 },
  my12: { marginVertical: CommonTokens.spacers.spacer12 },
  my14: { marginVertical: CommonTokens.spacers.spacer14 },
  my16: { marginVertical: CommonTokens.spacers.spacer16 },
  my18: { marginVertical: CommonTokens.spacers.spacer18 },
  my20: { marginVertical: CommonTokens.spacers.spacer20 },
  my22: { marginVertical: CommonTokens.spacers.spacer22 },
  my24: { marginVertical: CommonTokens.spacers.spacer24 },
  my26: { marginVertical: CommonTokens.spacers.spacer26 },
  my28: { marginVertical: CommonTokens.spacers.spacer28 },
  my30: { marginVertical: CommonTokens.spacers.spacer30 },
  my32: { marginVertical: CommonTokens.spacers.spacer32 },
  my36: { marginVertical: CommonTokens.spacers.spacer36 },
  my40: { marginVertical: CommonTokens.spacers.spacer40 },
  my44: { marginVertical: CommonTokens.spacers.spacer44 },
  my48: { marginVertical: CommonTokens.spacers.spacer48 },

  // ================  flex  ===================
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  flex3: { flex: 3 },

  flexRow: { flexDirection: 'row' },
  flexRowReverse: { flexDirection: 'row-reverse' },
  flexCol: { flexDirection: 'column' },
  flexColReverse: { flexDirection: 'column-reverse' },

  flexWrap: { flexWrap: 'wrap' },
  flexNoWrap: { flexWrap: 'nowrap' },
  flexWrapReverse: { flexWrap: 'wrap-reverse' },

  flexGrow0: { flexGrow: 0 },
  flexGrow1: { flexGrow: 1 },
  flexShrink0: { flexShrink: 0 },
  flexShrink1: { flexShrink: 1 },

  justifyStart: { justifyContent: 'flex-start' },
  justifyEnd: { justifyContent: 'flex-end' },
  justifyCenter: { justifyContent: 'center' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyAround: { justifyContent: 'space-around' },
  justifyEvenly: { justifyContent: 'space-evenly' },

  contentStart: { alignContent: 'flex-start' },
  contentEnd: { alignContent: 'flex-end' },
  contentCenter: { alignContent: 'center' },
  contentBetween: { alignContent: 'space-between' },
  contentAround: { alignContent: 'space-around' },
  contentStretch: { alignContent: 'stretch' },

  itemsStart: { alignItems: 'flex-start' },
  itemsEnd: { alignItems: 'flex-end' },
  itemsCenter: { alignItems: 'center' },
  itemsStretch: { alignItems: 'stretch' },
  itemsBaseline: { alignItems: 'baseline' },

  selfStart: { alignSelf: 'flex-start' },
  selfEnd: { alignSelf: 'flex-end' },
  selfCenter: { alignSelf: 'center' },
  selfStretch: { alignSelf: 'stretch' },
  selfBaseline: { alignSelf: 'baseline' },
  selfAuto: { alignSelf: 'auto' },

  flexCenter: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
  flexCenterH: { display: 'flex', justifyContent: 'center' },
  flexCenterV: { display: 'flex', alignItems: 'center' },
  flexBetween: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  flexBetweenH: { display: 'flex', justifyContent: 'space-between' },
  flexAround: { display: 'flex', justifyContent: 'space-around', alignItems: 'center' },
  flexAroundH: { display: 'flex', justifyContent: 'space-around' },
  flexEnd: { display: 'flex', alignItems: 'flex-end', justifyContent: 'center' },
  flexEndH: { display: 'flex', justifyContent: 'flex-end' },
  flexEndV: { display: 'flex', alignItems: 'flex-end' },
  flexStart: { display: 'flex', alignItems: 'flex-start', justifyContent: 'center' },
  flexStartH: { display: 'flex', justifyContent: 'flex-start' },
  flexStartV: { display: 'flex', alignItems: 'flex-start' },

  gap0: { gap: CommonTokens.spacers.spacer0 },
  gap2: { gap: CommonTokens.spacers.spacer2 },
  gap4: { gap: CommonTokens.spacers.spacer4 },
  gap6: { gap: CommonTokens.spacers.spacer6 },
  gap8: { gap: CommonTokens.spacers.spacer8 },
  gap10: { gap: CommonTokens.spacers.spacer10 },
  gap12: { gap: CommonTokens.spacers.spacer12 },
  gap14: { gap: CommonTokens.spacers.spacer14 },
  gap16: { gap: CommonTokens.spacers.spacer16 },
  gap18: { gap: CommonTokens.spacers.spacer18 },
  gap20: { gap: CommonTokens.spacers.spacer20 },
  gap22: { gap: CommonTokens.spacers.spacer22 },
  gap24: { gap: CommonTokens.spacers.spacer24 },

  gapX0: { columnGap: CommonTokens.spacers.spacer0 },
  gapX2: { columnGap: CommonTokens.spacers.spacer2 },
  gapX4: { columnGap: CommonTokens.spacers.spacer4 },
  gapX6: { columnGap: CommonTokens.spacers.spacer6 },
  gapX8: { columnGap: CommonTokens.spacers.spacer8 },
  gapX10: { columnGap: CommonTokens.spacers.spacer10 },
  gapX12: { columnGap: CommonTokens.spacers.spacer12 },
  gapX14: { columnGap: CommonTokens.spacers.spacer14 },
  gapX16: { columnGap: CommonTokens.spacers.spacer16 },
  gapX18: { columnGap: CommonTokens.spacers.spacer18 },
  gapX20: { columnGap: CommonTokens.spacers.spacer20 },
  gapX22: { columnGap: CommonTokens.spacers.spacer22 },
  gapX24: { columnGap: CommonTokens.spacers.spacer24 },

  gapY0: { rowGap: CommonTokens.spacers.spacer0 },
  gapY2: { rowGap: CommonTokens.spacers.spacer2 },
  gapY4: { rowGap: CommonTokens.spacers.spacer4 },
  gapY6: { rowGap: CommonTokens.spacers.spacer6 },
  gapY8: { rowGap: CommonTokens.spacers.spacer8 },
  gapY10: { rowGap: CommonTokens.spacers.spacer10 },
  gapY12: { rowGap: CommonTokens.spacers.spacer12 },
  gapY14: { rowGap: CommonTokens.spacers.spacer14 },
  gapY16: { rowGap: CommonTokens.spacers.spacer16 },
  gapY18: { rowGap: CommonTokens.spacers.spacer18 },
  gapY20: { rowGap: CommonTokens.spacers.spacer20 },
  gapY22: { rowGap: CommonTokens.spacers.spacer22 },
  gapY24: { rowGap: CommonTokens.spacers.spacer24 },

  // ================  圆角  ===================
  rounded0: { borderRadius: CommonTokens.spacers.spacer0 },
  roundedSm: { borderRadius: CommonTokens.radius.small },
  rounded: { borderRadius: CommonTokens.radius.default },
  roundedMd: { borderRadius: CommonTokens.radius.medium },
  roundedLg: { borderRadius: CommonTokens.radius.large },
  roundedXl: { borderRadius: CommonTokens.radius.xlarge },
  roundedFull: { borderRadius: CommonTokens.radius.round },

  // ================  对齐  ===================
  textCenter: { textAlign: 'center' },
  textRight: { textAlign: 'right' },
  textLeft: { textAlign: 'left' },
  textJustfy: { textAlign: 'justify' },

  // ================  显示  ===================
  hidden: { display: 'none' },

  // ================  字体  ===================
  text1: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xxxl,
    lineHeight: CommonTokens.lineHeight.xxxl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text1b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xxxl,
    lineHeight: CommonTokens.lineHeight.xxxl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text2: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xxl,
    lineHeight: CommonTokens.lineHeight.xxl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text2b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xxl,
    lineHeight: CommonTokens.lineHeight.xxl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text3: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xl,
    lineHeight: CommonTokens.lineHeight.xl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text3b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xl,
    lineHeight: CommonTokens.lineHeight.xl,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text4: {
    fontFamily,
    fontSize: CommonTokens.fontSize.l,
    lineHeight: CommonTokens.lineHeight.l,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text4b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.l,
    lineHeight: CommonTokens.lineHeight.l,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text5: {
    fontFamily,
    fontSize: CommonTokens.fontSize.base,
    lineHeight: CommonTokens.lineHeight.base,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text5b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.base,
    lineHeight: CommonTokens.lineHeight.base,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text6: {
    fontFamily,
    fontSize: CommonTokens.fontSize.s,
    lineHeight: CommonTokens.lineHeight.s,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text6b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.s,
    lineHeight: CommonTokens.lineHeight.s,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
  text7: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xs,
    lineHeight: CommonTokens.lineHeight.xs,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.normal,
  },
  text7b: {
    fontFamily,
    fontSize: CommonTokens.fontSize.xs,
    lineHeight: CommonTokens.lineHeight.xs,
    fontStyle: 'normal',
    fontWeight: CommonTokens.fontWeight.bold,
  },
};
