// import { IThemeCommonAtom } from '../types';
import { Platform, ViewStyle, TextStyle } from 'react-native';
import { CommonTokens } from './tokens';
import { CommonTokensType } from '../types';

const fontFamily = Platform.select({ android: 'sans-serif', ios: 'Helvetica' });

export function commonClassNames(tokens: CommonTokensType = CommonTokens): Record<string, ViewStyle | TextStyle> {
  return {
    // ================  内边距  ===================
    p0: { padding: tokens.spacers.spacer0 },
    p2: { padding: tokens.spacers.spacer2 },
    p4: { padding: tokens.spacers.spacer4 },
    p6: { padding: tokens.spacers.spacer6 },
    p8: { padding: tokens.spacers.spacer8 },
    p10: { padding: tokens.spacers.spacer10 },
    p12: { padding: tokens.spacers.spacer12 },
    p14: { padding: tokens.spacers.spacer14 },
    p16: { padding: tokens.spacers.spacer16 },
    p18: { padding: tokens.spacers.spacer18 },
    p20: { padding: tokens.spacers.spacer20 },
    p22: { padding: tokens.spacers.spacer22 },
    p24: { padding: tokens.spacers.spacer24 },
    p26: { padding: tokens.spacers.spacer26 },
    p28: { padding: tokens.spacers.spacer28 },
    p30: { padding: tokens.spacers.spacer30 },
    p32: { padding: tokens.spacers.spacer32 },
    p36: { padding: tokens.spacers.spacer36 },
    p40: { padding: tokens.spacers.spacer40 },
    p44: { padding: tokens.spacers.spacer44 },
    p48: { padding: tokens.spacers.spacer48 },

    pb0: { paddingBottom: tokens.spacers.spacer0 },
    pb2: { paddingBottom: tokens.spacers.spacer2 },
    pb4: { paddingBottom: tokens.spacers.spacer4 },
    pb6: { paddingBottom: tokens.spacers.spacer6 },
    pb8: { paddingBottom: tokens.spacers.spacer8 },
    pb10: { paddingBottom: tokens.spacers.spacer10 },
    pb12: { paddingBottom: tokens.spacers.spacer12 },
    pb14: { paddingBottom: tokens.spacers.spacer14 },
    pb16: { paddingBottom: tokens.spacers.spacer16 },
    pb18: { paddingBottom: tokens.spacers.spacer18 },
    pb20: { paddingBottom: tokens.spacers.spacer20 },
    pb22: { paddingBottom: tokens.spacers.spacer22 },
    pb24: { paddingBottom: tokens.spacers.spacer24 },
    pb26: { paddingBottom: tokens.spacers.spacer26 },
    pb28: { paddingBottom: tokens.spacers.spacer28 },
    pb30: { paddingBottom: tokens.spacers.spacer30 },
    pb32: { paddingBottom: tokens.spacers.spacer32 },
    pb36: { paddingBottom: tokens.spacers.spacer36 },
    pb40: { paddingBottom: tokens.spacers.spacer40 },
    pb44: { paddingBottom: tokens.spacers.spacer44 },
    pb48: { paddingBottom: tokens.spacers.spacer48 },

    pt0: { paddingTop: tokens.spacers.spacer0 },
    pt2: { paddingTop: tokens.spacers.spacer2 },
    pt4: { paddingTop: tokens.spacers.spacer4 },
    pt6: { paddingTop: tokens.spacers.spacer6 },
    pt8: { paddingTop: tokens.spacers.spacer8 },
    pt10: { paddingTop: tokens.spacers.spacer10 },
    pt12: { paddingTop: tokens.spacers.spacer12 },
    pt14: { paddingTop: tokens.spacers.spacer14 },
    pt16: { paddingTop: tokens.spacers.spacer16 },
    pt18: { paddingTop: tokens.spacers.spacer18 },
    pt20: { paddingTop: tokens.spacers.spacer20 },
    pt22: { paddingTop: tokens.spacers.spacer22 },
    pt24: { paddingTop: tokens.spacers.spacer24 },
    pt26: { paddingTop: tokens.spacers.spacer26 },
    pt28: { paddingTop: tokens.spacers.spacer28 },
    pt30: { paddingTop: tokens.spacers.spacer30 },
    pt32: { paddingTop: tokens.spacers.spacer32 },
    pt36: { paddingTop: tokens.spacers.spacer36 },
    pt40: { paddingTop: tokens.spacers.spacer40 },
    pt44: { paddingTop: tokens.spacers.spacer44 },
    pt48: { paddingTop: tokens.spacers.spacer48 },

    pl0: { paddingLeft: tokens.spacers.spacer0 },
    pl2: { paddingLeft: tokens.spacers.spacer2 },
    pl4: { paddingLeft: tokens.spacers.spacer4 },
    pl6: { paddingLeft: tokens.spacers.spacer6 },
    pl8: { paddingLeft: tokens.spacers.spacer8 },
    pl10: { paddingLeft: tokens.spacers.spacer10 },
    pl12: { paddingLeft: tokens.spacers.spacer12 },
    pl14: { paddingLeft: tokens.spacers.spacer14 },
    pl16: { paddingLeft: tokens.spacers.spacer16 },
    pl18: { paddingLeft: tokens.spacers.spacer18 },
    pl20: { paddingLeft: tokens.spacers.spacer20 },
    pl22: { paddingLeft: tokens.spacers.spacer22 },
    pl24: { paddingLeft: tokens.spacers.spacer24 },
    pl26: { paddingLeft: tokens.spacers.spacer26 },
    pl28: { paddingLeft: tokens.spacers.spacer28 },
    pl30: { paddingLeft: tokens.spacers.spacer30 },
    pl32: { paddingLeft: tokens.spacers.spacer32 },
    pl36: { paddingLeft: tokens.spacers.spacer36 },
    pl40: { paddingLeft: tokens.spacers.spacer40 },
    pl44: { paddingLeft: tokens.spacers.spacer44 },
    pl48: { paddingLeft: tokens.spacers.spacer48 },

    pr0: { paddingRight: tokens.spacers.spacer0 },
    pr2: { paddingRight: tokens.spacers.spacer2 },
    pr4: { paddingRight: tokens.spacers.spacer4 },
    pr6: { paddingRight: tokens.spacers.spacer6 },
    pr8: { paddingRight: tokens.spacers.spacer8 },
    pr10: { paddingRight: tokens.spacers.spacer10 },
    pr12: { paddingRight: tokens.spacers.spacer12 },
    pr14: { paddingRight: tokens.spacers.spacer14 },
    pr16: { paddingRight: tokens.spacers.spacer16 },
    pr18: { paddingRight: tokens.spacers.spacer18 },
    pr20: { paddingRight: tokens.spacers.spacer20 },
    pr22: { paddingRight: tokens.spacers.spacer22 },
    pr24: { paddingRight: tokens.spacers.spacer24 },
    pr26: { paddingRight: tokens.spacers.spacer26 },
    pr28: { paddingRight: tokens.spacers.spacer28 },
    pr30: { paddingRight: tokens.spacers.spacer30 },
    pr32: { paddingRight: tokens.spacers.spacer32 },
    pr36: { paddingRight: tokens.spacers.spacer36 },
    pr40: { paddingRight: tokens.spacers.spacer40 },
    pr44: { paddingRight: tokens.spacers.spacer44 },
    pr48: { paddingRight: tokens.spacers.spacer48 },

    px0: { paddingHorizontal: tokens.spacers.spacer0 },
    px2: { paddingHorizontal: tokens.spacers.spacer2 },
    px4: { paddingHorizontal: tokens.spacers.spacer4 },
    px6: { paddingHorizontal: tokens.spacers.spacer6 },
    px8: { paddingHorizontal: tokens.spacers.spacer8 },
    px10: { paddingHorizontal: tokens.spacers.spacer10 },
    px12: { paddingHorizontal: tokens.spacers.spacer12 },
    px14: { paddingHorizontal: tokens.spacers.spacer14 },
    px16: { paddingHorizontal: tokens.spacers.spacer16 },
    px18: { paddingHorizontal: tokens.spacers.spacer18 },
    px20: { paddingHorizontal: tokens.spacers.spacer20 },
    px22: { paddingHorizontal: tokens.spacers.spacer22 },
    px24: { paddingHorizontal: tokens.spacers.spacer24 },
    px26: { paddingHorizontal: tokens.spacers.spacer26 },
    px28: { paddingHorizontal: tokens.spacers.spacer28 },
    px30: { paddingHorizontal: tokens.spacers.spacer30 },
    px32: { paddingHorizontal: tokens.spacers.spacer32 },
    px36: { paddingHorizontal: tokens.spacers.spacer36 },
    px40: { paddingHorizontal: tokens.spacers.spacer40 },
    px44: { paddingHorizontal: tokens.spacers.spacer44 },
    px48: { paddingHorizontal: tokens.spacers.spacer48 },

    py0: { paddingVertical: tokens.spacers.spacer0 },
    py2: { paddingVertical: tokens.spacers.spacer2 },
    py4: { paddingVertical: tokens.spacers.spacer4 },
    py6: { paddingVertical: tokens.spacers.spacer6 },
    py8: { paddingVertical: tokens.spacers.spacer8 },
    py10: { paddingVertical: tokens.spacers.spacer10 },
    py12: { paddingVertical: tokens.spacers.spacer12 },
    py14: { paddingVertical: tokens.spacers.spacer14 },
    py16: { paddingVertical: tokens.spacers.spacer16 },
    py18: { paddingVertical: tokens.spacers.spacer18 },
    py20: { paddingVertical: tokens.spacers.spacer20 },
    py22: { paddingVertical: tokens.spacers.spacer22 },
    py24: { paddingVertical: tokens.spacers.spacer24 },
    py26: { paddingVertical: tokens.spacers.spacer26 },
    py28: { paddingVertical: tokens.spacers.spacer28 },
    py30: { paddingVertical: tokens.spacers.spacer30 },
    py32: { paddingVertical: tokens.spacers.spacer32 },
    py36: { paddingVertical: tokens.spacers.spacer36 },
    py40: { paddingVertical: tokens.spacers.spacer40 },
    py44: { paddingVertical: tokens.spacers.spacer44 },
    py48: { paddingVertical: tokens.spacers.spacer48 },

    // ================  外边距  ===================
    m0: { margin: tokens.spacers.spacer0 },
    m2: { margin: tokens.spacers.spacer2 },
    m4: { margin: tokens.spacers.spacer4 },
    m6: { margin: tokens.spacers.spacer6 },
    m8: { margin: tokens.spacers.spacer8 },
    m10: { margin: tokens.spacers.spacer10 },
    m12: { margin: tokens.spacers.spacer12 },
    m14: { margin: tokens.spacers.spacer14 },
    m16: { margin: tokens.spacers.spacer16 },
    m18: { margin: tokens.spacers.spacer18 },
    m20: { margin: tokens.spacers.spacer20 },
    m22: { margin: tokens.spacers.spacer22 },
    m24: { margin: tokens.spacers.spacer24 },
    m26: { margin: tokens.spacers.spacer26 },
    m28: { margin: tokens.spacers.spacer28 },
    m30: { margin: tokens.spacers.spacer30 },
    m32: { margin: tokens.spacers.spacer32 },
    m36: { margin: tokens.spacers.spacer36 },
    m40: { margin: tokens.spacers.spacer40 },
    m44: { margin: tokens.spacers.spacer44 },
    m48: { margin: tokens.spacers.spacer48 },

    mb0: { marginBottom: tokens.spacers.spacer0 },
    mb2: { marginBottom: tokens.spacers.spacer2 },
    mb4: { marginBottom: tokens.spacers.spacer4 },
    mb6: { marginBottom: tokens.spacers.spacer6 },
    mb8: { marginBottom: tokens.spacers.spacer8 },
    mb10: { marginBottom: tokens.spacers.spacer10 },
    mb12: { marginBottom: tokens.spacers.spacer12 },
    mb14: { marginBottom: tokens.spacers.spacer14 },
    mb16: { marginBottom: tokens.spacers.spacer16 },
    mb18: { marginBottom: tokens.spacers.spacer18 },
    mb20: { marginBottom: tokens.spacers.spacer20 },
    mb22: { marginBottom: tokens.spacers.spacer22 },
    mb24: { marginBottom: tokens.spacers.spacer24 },
    mb26: { marginBottom: tokens.spacers.spacer26 },
    mb28: { marginBottom: tokens.spacers.spacer28 },
    mb30: { marginBottom: tokens.spacers.spacer30 },
    mb32: { marginBottom: tokens.spacers.spacer32 },
    mb36: { marginBottom: tokens.spacers.spacer36 },
    mb40: { marginBottom: tokens.spacers.spacer40 },
    mb44: { marginBottom: tokens.spacers.spacer44 },
    mb48: { marginBottom: tokens.spacers.spacer48 },

    mt0: { marginTop: tokens.spacers.spacer0 },
    mt2: { marginTop: tokens.spacers.spacer2 },
    mt4: { marginTop: tokens.spacers.spacer4 },
    mt6: { marginTop: tokens.spacers.spacer6 },
    mt8: { marginTop: tokens.spacers.spacer8 },
    mt10: { marginTop: tokens.spacers.spacer10 },
    mt12: { marginTop: tokens.spacers.spacer12 },
    mt14: { marginTop: tokens.spacers.spacer14 },
    mt16: { marginTop: tokens.spacers.spacer16 },
    mt18: { marginTop: tokens.spacers.spacer18 },
    mt20: { marginTop: tokens.spacers.spacer20 },
    mt22: { marginTop: tokens.spacers.spacer22 },
    mt24: { marginTop: tokens.spacers.spacer24 },
    mt26: { marginTop: tokens.spacers.spacer26 },
    mt28: { marginTop: tokens.spacers.spacer28 },
    mt30: { marginTop: tokens.spacers.spacer30 },
    mt32: { marginTop: tokens.spacers.spacer32 },
    mt36: { marginTop: tokens.spacers.spacer36 },
    mt40: { marginTop: tokens.spacers.spacer40 },
    mt44: { marginTop: tokens.spacers.spacer44 },
    mt48: { marginTop: tokens.spacers.spacer48 },

    ml0: { marginLeft: tokens.spacers.spacer0 },
    ml2: { marginLeft: tokens.spacers.spacer2 },
    ml4: { marginLeft: tokens.spacers.spacer4 },
    ml6: { marginLeft: tokens.spacers.spacer6 },
    ml8: { marginLeft: tokens.spacers.spacer8 },
    ml10: { marginLeft: tokens.spacers.spacer10 },
    ml12: { marginLeft: tokens.spacers.spacer12 },
    ml14: { marginLeft: tokens.spacers.spacer14 },
    ml16: { marginLeft: tokens.spacers.spacer16 },
    ml18: { marginLeft: tokens.spacers.spacer18 },
    ml20: { marginLeft: tokens.spacers.spacer20 },
    ml22: { marginLeft: tokens.spacers.spacer22 },
    ml24: { marginLeft: tokens.spacers.spacer24 },
    ml26: { marginLeft: tokens.spacers.spacer26 },
    ml28: { marginLeft: tokens.spacers.spacer28 },
    ml30: { marginLeft: tokens.spacers.spacer30 },
    ml32: { marginLeft: tokens.spacers.spacer32 },
    ml36: { marginLeft: tokens.spacers.spacer36 },
    ml40: { marginLeft: tokens.spacers.spacer40 },
    ml44: { marginLeft: tokens.spacers.spacer44 },
    ml48: { marginLeft: tokens.spacers.spacer48 },

    mr0: { marginRight: tokens.spacers.spacer0 },
    mr2: { marginRight: tokens.spacers.spacer2 },
    mr4: { marginRight: tokens.spacers.spacer4 },
    mr6: { marginRight: tokens.spacers.spacer6 },
    mr8: { marginRight: tokens.spacers.spacer8 },
    mr10: { marginRight: tokens.spacers.spacer10 },
    mr12: { marginRight: tokens.spacers.spacer12 },
    mr14: { marginRight: tokens.spacers.spacer14 },
    mr16: { marginRight: tokens.spacers.spacer16 },
    mr18: { marginRight: tokens.spacers.spacer18 },
    mr20: { marginRight: tokens.spacers.spacer20 },
    mr22: { marginRight: tokens.spacers.spacer22 },
    mr24: { marginRight: tokens.spacers.spacer24 },
    mr26: { marginRight: tokens.spacers.spacer26 },
    mr28: { marginRight: tokens.spacers.spacer28 },
    mr30: { marginRight: tokens.spacers.spacer30 },
    mr32: { marginRight: tokens.spacers.spacer32 },
    mr36: { marginRight: tokens.spacers.spacer36 },
    mr40: { marginRight: tokens.spacers.spacer40 },
    mr44: { marginRight: tokens.spacers.spacer44 },
    mr48: { marginRight: tokens.spacers.spacer48 },

    mx0: { marginHorizontal: tokens.spacers.spacer0 },
    mx2: { marginHorizontal: tokens.spacers.spacer2 },
    mx4: { marginHorizontal: tokens.spacers.spacer4 },
    mx6: { marginHorizontal: tokens.spacers.spacer6 },
    mx8: { marginHorizontal: tokens.spacers.spacer8 },
    mx10: { marginHorizontal: tokens.spacers.spacer10 },
    mx12: { marginHorizontal: tokens.spacers.spacer12 },
    mx14: { marginHorizontal: tokens.spacers.spacer14 },
    mx16: { marginHorizontal: tokens.spacers.spacer16 },
    mx18: { marginHorizontal: tokens.spacers.spacer18 },
    mx20: { marginHorizontal: tokens.spacers.spacer20 },
    mx22: { marginHorizontal: tokens.spacers.spacer22 },
    mx24: { marginHorizontal: tokens.spacers.spacer24 },
    mx26: { marginHorizontal: tokens.spacers.spacer26 },
    mx28: { marginHorizontal: tokens.spacers.spacer28 },
    mx30: { marginHorizontal: tokens.spacers.spacer30 },
    mx32: { marginHorizontal: tokens.spacers.spacer32 },
    mx36: { marginHorizontal: tokens.spacers.spacer36 },
    mx40: { marginHorizontal: tokens.spacers.spacer40 },
    mx44: { marginHorizontal: tokens.spacers.spacer44 },
    mx48: { marginHorizontal: tokens.spacers.spacer48 },

    my0: { marginVertical: tokens.spacers.spacer0 },
    my2: { marginVertical: tokens.spacers.spacer2 },
    my4: { marginVertical: tokens.spacers.spacer4 },
    my6: { marginVertical: tokens.spacers.spacer6 },
    my8: { marginVertical: tokens.spacers.spacer8 },
    my10: { marginVertical: tokens.spacers.spacer10 },
    my12: { marginVertical: tokens.spacers.spacer12 },
    my14: { marginVertical: tokens.spacers.spacer14 },
    my16: { marginVertical: tokens.spacers.spacer16 },
    my18: { marginVertical: tokens.spacers.spacer18 },
    my20: { marginVertical: tokens.spacers.spacer20 },
    my22: { marginVertical: tokens.spacers.spacer22 },
    my24: { marginVertical: tokens.spacers.spacer24 },
    my26: { marginVertical: tokens.spacers.spacer26 },
    my28: { marginVertical: tokens.spacers.spacer28 },
    my30: { marginVertical: tokens.spacers.spacer30 },
    my32: { marginVertical: tokens.spacers.spacer32 },
    my36: { marginVertical: tokens.spacers.spacer36 },
    my40: { marginVertical: tokens.spacers.spacer40 },
    my44: { marginVertical: tokens.spacers.spacer44 },
    my48: { marginVertical: tokens.spacers.spacer48 },

    // ================  flex  ===================
    flex1: { flex: 1 },
    flex2: { flex: 2 },
    flex3: { flex: 3 },

    flexRow: { flexDirection: 'row' },
    flexRowReverse: { flexDirection: 'row-reverse' },
    flexCol: { flexDirection: 'column' },
    flexColReverse: { flexDirection: 'column-reverse' },

    flexWrap: { flexWrap: 'wrap' },
    flexNoWrap: { flexWrap: 'nowrap' },
    flexWrapReverse: { flexWrap: 'wrap-reverse' },

    flexGrow0: { flexGrow: 0 },
    flexGrow1: { flexGrow: 1 },
    flexShrink0: { flexShrink: 0 },
    flexShrink1: { flexShrink: 1 },

    justifyStart: { justifyContent: 'flex-start' },
    justifyEnd: { justifyContent: 'flex-end' },
    justifyCenter: { justifyContent: 'center' },
    justifyBetween: { justifyContent: 'space-between' },
    justifyAround: { justifyContent: 'space-around' },
    justifyEvenly: { justifyContent: 'space-evenly' },

    contentStart: { alignContent: 'flex-start' },
    contentEnd: { alignContent: 'flex-end' },
    contentCenter: { alignContent: 'center' },
    contentBetween: { alignContent: 'space-between' },
    contentAround: { alignContent: 'space-around' },
    contentStretch: { alignContent: 'stretch' },

    itemsStart: { alignItems: 'flex-start' },
    itemsEnd: { alignItems: 'flex-end' },
    itemsCenter: { alignItems: 'center' },
    itemsStretch: { alignItems: 'stretch' },
    itemsBaseline: { alignItems: 'baseline' },

    selfStart: { alignSelf: 'flex-start' },
    selfEnd: { alignSelf: 'flex-end' },
    selfCenter: { alignSelf: 'center' },
    selfStretch: { alignSelf: 'stretch' },
    selfBaseline: { alignSelf: 'baseline' },
    selfAuto: { alignSelf: 'auto' },

    flexCenter: { display: 'flex', justifyContent: 'center', alignItems: 'center' },
    flexCenterH: { display: 'flex', justifyContent: 'center' },
    flexCenterV: { display: 'flex', alignItems: 'center' },
    flexBetween: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    flexBetweenH: { display: 'flex', justifyContent: 'space-between' },
    flexAround: { display: 'flex', justifyContent: 'space-around', alignItems: 'center' },
    flexAroundH: { display: 'flex', justifyContent: 'space-around' },
    flexEnd: { display: 'flex', justifyContent: 'flex-end', alignItems: 'center' },
    flexEndH: { display: 'flex', justifyContent: 'flex-end' },
    flexEndV: { display: 'flex', alignItems: 'flex-end' },
    flexStart: { display: 'flex', justifyContent: 'flex-start', alignItems: 'center' },
    flexStartH: { display: 'flex', justifyContent: 'flex-start' },
    flexStartV: { display: 'flex', alignItems: 'flex-start' },

    gap0: { gap: tokens.spacers.spacer0 },
    gap2: { gap: tokens.spacers.spacer2 },
    gap4: { gap: tokens.spacers.spacer4 },
    gap6: { gap: tokens.spacers.spacer6 },
    gap8: { gap: tokens.spacers.spacer8 },
    gap10: { gap: tokens.spacers.spacer10 },
    gap12: { gap: tokens.spacers.spacer12 },
    gap14: { gap: tokens.spacers.spacer14 },
    gap16: { gap: tokens.spacers.spacer16 },
    gap18: { gap: tokens.spacers.spacer18 },
    gap20: { gap: tokens.spacers.spacer20 },
    gap22: { gap: tokens.spacers.spacer22 },
    gap24: { gap: tokens.spacers.spacer24 },

    gapX0: { columnGap: tokens.spacers.spacer0 },
    gapX2: { columnGap: tokens.spacers.spacer2 },
    gapX4: { columnGap: tokens.spacers.spacer4 },
    gapX6: { columnGap: tokens.spacers.spacer6 },
    gapX8: { columnGap: tokens.spacers.spacer8 },
    gapX10: { columnGap: tokens.spacers.spacer10 },
    gapX12: { columnGap: tokens.spacers.spacer12 },
    gapX14: { columnGap: tokens.spacers.spacer14 },
    gapX16: { columnGap: tokens.spacers.spacer16 },
    gapX18: { columnGap: tokens.spacers.spacer18 },
    gapX20: { columnGap: tokens.spacers.spacer20 },
    gapX22: { columnGap: tokens.spacers.spacer22 },
    gapX24: { columnGap: tokens.spacers.spacer24 },

    gapY0: { rowGap: tokens.spacers.spacer0 },
    gapY2: { rowGap: tokens.spacers.spacer2 },
    gapY4: { rowGap: tokens.spacers.spacer4 },
    gapY6: { rowGap: tokens.spacers.spacer6 },
    gapY8: { rowGap: tokens.spacers.spacer8 },
    gapY10: { rowGap: tokens.spacers.spacer10 },
    gapY12: { rowGap: tokens.spacers.spacer12 },
    gapY14: { rowGap: tokens.spacers.spacer14 },
    gapY16: { rowGap: tokens.spacers.spacer16 },
    gapY18: { rowGap: tokens.spacers.spacer18 },
    gapY20: { rowGap: tokens.spacers.spacer20 },
    gapY22: { rowGap: tokens.spacers.spacer22 },
    gapY24: { rowGap: tokens.spacers.spacer24 },

    // ================  圆角  ===================
    rounded0: { borderRadius: tokens.spacers.spacer0 },
    roundedSm: { borderRadius: tokens.radius.small },
    rounded: { borderRadius: tokens.radius.default },
    roundedMd: { borderRadius: tokens.radius.medium },
    roundedLg: { borderRadius: tokens.radius.large },
    roundedXl: { borderRadius: tokens.radius.xlarge },
    roundedFull: { borderRadius: tokens.radius.round },

    // ================  对齐  ===================
    textCenter: { textAlign: 'center' },
    textRight: { textAlign: 'right' },
    textLeft: { textAlign: 'left' },
    textJustfy: { textAlign: 'justify' },

    // ================  显示  ===================
    hidden: { display: 'none' },

    // ================  字体  ===================
    text1: {
      fontFamily,
      fontSize: tokens.fontSize.xxxl,
      lineHeight: tokens.lineHeight.xxxl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text1b: {
      fontFamily,
      fontSize: tokens.fontSize.xxxl,
      lineHeight: tokens.lineHeight.xxxl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text2: {
      fontFamily,
      fontSize: tokens.fontSize.xxl,
      lineHeight: tokens.lineHeight.xxl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text2b: {
      fontFamily,
      fontSize: tokens.fontSize.xxl,
      lineHeight: tokens.lineHeight.xxl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text3: {
      fontFamily,
      fontSize: tokens.fontSize.xl,
      lineHeight: tokens.lineHeight.xl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text3b: {
      fontFamily,
      fontSize: tokens.fontSize.xl,
      lineHeight: tokens.lineHeight.xl,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text4: {
      fontFamily,
      fontSize: tokens.fontSize.l,
      lineHeight: tokens.lineHeight.l,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text4b: {
      fontFamily,
      fontSize: tokens.fontSize.l,
      lineHeight: tokens.lineHeight.l,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text5: {
      fontFamily,
      fontSize: tokens.fontSize.base,
      lineHeight: tokens.lineHeight.base,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text5b: {
      fontFamily,
      fontSize: tokens.fontSize.base,
      lineHeight: tokens.lineHeight.base,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text6: {
      fontFamily,
      fontSize: tokens.fontSize.s,
      lineHeight: tokens.lineHeight.s,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text6b: {
      fontFamily,
      fontSize: tokens.fontSize.s,
      lineHeight: tokens.lineHeight.s,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
    text7: {
      fontFamily,
      fontSize: tokens.fontSize.xs,
      lineHeight: tokens.lineHeight.xs,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.normal,
    },
    text7b: {
      fontFamily,
      fontSize: tokens.fontSize.xs,
      lineHeight: tokens.lineHeight.xs,
      fontStyle: 'normal',
      fontWeight: tokens.fontWeight.bold,
    },
  };
}
