import { FontSize, FontWeight } from './fonts';
import { Spacers } from './spacers';

export const CommonTokens = {
  fontSize: {
    xs: FontSize.xs,
    s: FontSize.s,
    base: FontSize.base,
    l: FontSize.l,
    xl: FontSize.xl,
    xxl: FontSize.xxl,
    xxxl: FontSize.xxxl,
  },
  lineHeight: {
    xs: Spacers.spacer16,
    s: Spacers.spacer20,
    base: Spacers.spacer22,
    l: Spacers.spacer24,
    xl: Spacers.spacer26,
    xxl: Spacers.spacer30,
    xxxl: Spacers.spacer44,
  },
  radius: {
    small: Spacers.spacer2,
    default: Spacers.spacer4,
    medium: Spacers.spacer6,
    large: Spacers.spacer8,
    xlarge: Spacers.spacer10,
    round: Spacers.spacer999,
  },
  fontWeight: {
    thin: FontWeight.thin,
    extralight: FontWeight.extralight,
    light: FontWeight.light,
    normal: FontWeight.normal,
    medium: FontWeight.medium,
    semibold: FontWeight.semibold,
    bold: FontWeight.bold,
    extrabold: FontWeight.extrabold,
    black: FontWeight.black,
  },
  spacers: {
    spacer0: Spacers.spacer0,
    spacer1: Spacers.spacer1,
    spacer2: Spacers.spacer2,
    spacer4: Spacers.spacer4,
    spacer6: Spacers.spacer6,
    spacer8: Spacers.spacer8,
    spacer10: Spacers.spacer10,
    spacer12: Spacers.spacer12,
    spacer14: Spacers.spacer14,
    spacer16: Spacers.spacer16,
    spacer18: Spacers.spacer18,
    spacer20: Spacers.spacer20,
    spacer22: Spacers.spacer22,
    spacer24: Spacers.spacer24,
    spacer26: Spacers.spacer26,
    spacer28: Spacers.spacer28,
    spacer30: Spacers.spacer30,
    spacer32: Spacers.spacer32,
    spacer36: Spacers.spacer36,
    spacer40: Spacers.spacer40,
    spacer44: Spacers.spacer44,
    spacer48: Spacers.spacer48,
    spacer52: Spacers.spacer52,
    spacer56: Spacers.spacer56,
    spacer60: Spacers.spacer60,
    spacer64: Spacers.spacer64,
    spacer68: Spacers.spacer68,
    spacer72: Spacers.spacer72,
    spacer76: Spacers.spacer76,
    spacer80: Spacers.spacer80,
    spacer84: Spacers.spacer84,
    spacer88: Spacers.spacer88,
    spacer92: Spacers.spacer92,
    spacer96: Spacers.spacer96,
    spacer100: Spacers.spacer100,
    spacer104: Spacers.spacer104,
    spacer108: Spacers.spacer108,
    spacer112: Spacers.spacer112,
    spacer116: Spacers.spacer116,
    spacer120: Spacers.spacer120,
    spacer124: Spacers.spacer124,
    spacer128: Spacers.spacer128,
    spacer132: Spacers.spacer132,
    spacer136: Spacers.spacer136,
    spacer140: Spacers.spacer140,
    spacer144: Spacers.spacer144,
    spacer148: Spacers.spacer148,
    spacer156: Spacers.spacer156,
    spacer160: Spacers.spacer160,
    spacer999: Spacers.spacer999,
  },
};
