import { DarkColors } from './colors';
import { CommonTokens } from '../common/tokens';

export const darkTokens = {
  ...CommonTokens,
  colors: {
    white: DarkColors.white,
    brand1: DarkColors.brand1,
    brand2: DarkColors.brand2,
    brand3: DarkColors.brand3,
    brand4: DarkColors.brand4,
    brand5: DarkColors.brand5,
    brand6: DarkColors.brand6,
    brand7: DarkColors.brand7,
    brand8: DarkColors.brand8,
    brand9: DarkColors.brand9,
    brand10: DarkColors.brand10,
    brand: DarkColors.brand8,
    brandLight: DarkColors.brand1,
    brandFocus: DarkColors.brand2,
    brandDisabled: DarkColors.brand3,
    brandHover: DarkColors.brand7,
    brandActive: DarkColors.brand9,

    error1: DarkColors.error1,
    error2: DarkColors.error2,
    error3: DarkColors.error3,
    error4: DarkColors.error4,
    error5: DarkColors.error5,
    error6: DarkColors.error6,
    error7: DarkColors.error7,
    error8: DarkColors.error8,
    error9: DarkColors.error9,
    error10: DarkColors.error10,
    error: DarkColors.error6,
    errorLight: DarkColors.error1,
    errorFocus: DarkColors.error2,
    errorDisabled: DarkColors.error3,
    errorHover: DarkColors.error2,
    errorActive: DarkColors.error7,

    success1: DarkColors.success1,
    success2: DarkColors.success2,
    success3: DarkColors.success3,
    success4: DarkColors.success4,
    success5: DarkColors.success5,
    success6: DarkColors.success6,
    success7: DarkColors.success7,
    success8: DarkColors.success8,
    success9: DarkColors.success9,
    success10: DarkColors.success10,
    success: DarkColors.success5,
    successLight: DarkColors.success1,
    successFocus: DarkColors.success2,
    successDisabled: DarkColors.success3,
    successHover: DarkColors.success4,
    successActive: DarkColors.success6,

    warning1: DarkColors.warning1,
    warning2: DarkColors.warning2,
    warning3: DarkColors.warning3,
    warning4: DarkColors.warning4,
    warning5: DarkColors.warning5,
    warning6: DarkColors.warning6,
    warning7: DarkColors.warning7,
    warning8: DarkColors.warning8,
    warning9: DarkColors.warning9,
    warning10: DarkColors.warning10,
    warning: DarkColors.warning5,
    warningLight: DarkColors.warning1,
    warningFocus: DarkColors.warning2,
    warningDisabled: DarkColors.warning3,
    warningHover: DarkColors.warning4,
    warningActive: DarkColors.warning6,

    gray1: DarkColors.gray1,
    gray2: DarkColors.gray2,
    gray3: DarkColors.gray3,
    gray4: DarkColors.gray4,
    gray5: DarkColors.gray5,
    gray6: DarkColors.gray6,
    gray7: DarkColors.gray7,
    gray8: DarkColors.gray8,
    gray9: DarkColors.gray9,
    gray10: DarkColors.gray10,
    gray11: DarkColors.gray11,
    gray12: DarkColors.gray12,
    gray13: DarkColors.gray13,
    gray14: DarkColors.gray14,

    bgPage: DarkColors.gray14,
    bgContainer: DarkColors.gray13,
    bgContainerHover: DarkColors.gray12,
    bgContainerActive: DarkColors.gray10,
    bgContainerSelect: DarkColors.gray9,
    bgSubContainer: DarkColors.gray12,
    bgSubContainerHover: DarkColors.gray11,
    bgSubContainerActive: DarkColors.gray9,
    bgComponent: DarkColors.gray11,
    bgComponentHover: DarkColors.gray10,
    bgComponentActive: DarkColors.gray9,
    bgComponentDisabled: DarkColors.gray12,
    bgSubComponent: DarkColors.gray10,
    bgSubComponentHover: DarkColors.gray9,
    bgSubComponentActive: DarkColors.gray8,

    componentStroke: DarkColors.gray11,
    componentBorder: DarkColors.gray9,

    fontWhite1: DarkColors.fontWhite1,
    fontWhite2: DarkColors.fontWhite2,
    fontWhite3: DarkColors.fontWhite3,
    fontWhite4: DarkColors.fontWhite4,

    fontGray1: DarkColors.fontGray1,
    fontGray2: DarkColors.fontGray2,
    fontGray3: DarkColors.fontGray3,
    fontGray4: DarkColors.fontGray4,

    textPrimary: DarkColors.fontWhite1,
    textSecondary: DarkColors.fontWhite2,
    textPlaceholder: DarkColors.fontWhite3,
    textDisabled: DarkColors.fontWhite4,
    textAnti: DarkColors.white,
    textBrand: DarkColors.brand7,
    textLink: DarkColors.brand7,

    shadow1: DarkColors.shadow1,
    shadow2: DarkColors.shadow2,
    shadow3: DarkColors.shadow3,
  },
};
